-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Apr 25, 2021 at 06:27 PM
-- Server version: 10.4.18-MariaDB
-- PHP Version: 7.3.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `HSI`
--

-- --------------------------------------------------------

--
-- Table structure for table `positions`
--

CREATE TABLE `positions` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `jobTitle` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `location` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `salary` int(11) NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `positions`
--

INSERT INTO `positions` (`id`, `jobTitle`, `location`, `salary`, `description`, `created_at`, `updated_at`) VALUES
(1, 'Food & Beverage Manager', 'Latvia', 3500, 'We are currently seeking a Food & Beverage Manager for a 4 star Hotel in Latvia, which is part of an international hotel group. The ideal candidate will assume full responsibility for the day-to-day operation of this department and will have a thorough knowledge of food and beverage operations including foods, beverages, supervisory aspects, service techniques, and guest interaction. You will be required to manage, train and develop team members and work within all budgeted guidelines. To be considered for this role you should have a minimum of 2 years experience holding an F&B management/assistant/supervisory role in a 4/5 star property and you will be holding a recognised qualification in a relevant field. All applicants must be eligible to work in Europe without the requirement of a visa. Due to the anticipated high level of response we will only be able to respond to those of you who are shortlisted.\r\n', '2021-04-05 14:46:08', '2021-04-05 14:46:08'),
(2, 'Resort Manager', 'Maldives', 9000, 'Beautiful Island Resort in the Maldives is looking to strengthen their senior management team with the appointment of a Resort Manager. Your role will be to ensure that the highest possible standards of guest hospitality, service and product are delivered, enhancing the guest experience yet maximising bottom line conversion.  Excellent communication skills are required. To apply for this role you will have 3 years experience in Revenue and you must be able to communicate fluently in English. Other language skills would be an added bonus. Island experience would be beneficial. A background in Rooms division would be preferred. A good salary package is on offer. Only shortlisted candidates will be responded to.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(3, 'Chief Financial Officer', 'Bahrain', 13000, 'We are currently seeking a Chief Financial Officer for a hotel company in Bahrain. Reporting to the Chief Executive Officer you will be a key member of the Executive Management team, playing a major strategic role in the overall management of the company. You will have primary day-to-day responsibility for planning, implementing, managing and controlling all financial-related activities of the company. This will include direct responsibility for financial strategic planning, accounting, finance, forecasting, legal affairs, asset management, tender and negotiations, policing and maintenance of policies and procedures and investment management. To be considered for this role you should have a minimum of 5 years’ experience in a senior corporate finance role in a recognized hospitality related company, coupled with at least 10 years’ experience in a senior property/unit role in the hotel sector. You will be holding an academic qualification of a Bachelor’s Degree in Accounting or Finance (but MBA level preferred) along with CPA qualification and you will have excellent English language skills.  A good salary is on offer and, whilst we thank you for your application, only shortlisted candidates will be responded to.  ', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(4, 'Restaurant Executive Chef', 'Nigeria', 7500, 'We are looking for a Restaurant Executive Chef to oversee the daily operations and requirements of a small Restaurant group in West Africa. They have a new operation opening and you will also be heavily involved in the set up of this project. The ideal candidate will be an enthusiastic \'hands-on\' professional with strong all round kitchen skills, passionate about cooking and capable of managing the production and delivery of a great product in this busy fresh food operation. You must be well organized and capable of delivering a quality product quickly and under pressure. Responsibilities will include the training and coaching of your kitchen workforce. To apply for this role you must have at least 10 years’ experience in a similar busy fresh food environment with a sound knowledge of continental cuisine and professional qualifications and relevant industry experience. Ideally you will have experience in a modern Restaurant company within a progressive city in the world, however we will consider a Hotel Executive Chef as long as you have an understanding of fashionable upscale restaurant concepts. Relevant working experience within Africa would be beneficial but not essential. An excellent salary is on offer. Please note that you will only be contacted if you are short listed.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(5, 'Finance Manager', 'Ghana', 5500, 'We are currently seeking a Finance Manager for a property in West Africa. Your purpose is to oversee and maintain accounting and financial requirements for the property. You will demonstrate hospitality through offering financial support, advice and expertise to the team. You will work with the General Manager to provide full and accurate forecasting and budgeting proposals, ensuring that all legislative requirements are met. To apply you should have a relevant qualification in Finance, Accounting or related business discipline, from a recognised academic institution and have previous experience working in the Accounts/Finance Management function within the hospitality industry. Only those of you who are short listed will be contacted.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(6, 'Food & Beverage Managers', 'South Africa', 5000, 'We are currently looking for Food & Beverage Managers who would like to be part of the development plans of an International company with various properties opening within Africa and the Indian Ocean, over the next 3-6 months.. The role will involve managing and achieving profit and quality for all food & beverage operations in the property, including restaurants, catering and banqueting. To apply for this role you will have a minimum 5 years’ experience in a leading hotel high quality F&B operation at similar level. You will need to have international 5 star experience with a solid background in management and you should have worked in Africa, the Indian Ocean or hardship locations. If you would like to be considered and become part of this growing International company, please forward your resume. Should you be suitable we will then share further details regarding this role.', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(7, 'Executive Chef', 'South Africa', 5000, 'We are currently looking for Executive Chefs who would like to be part of the development plans of an International company with various properties opening within Africa and the Indian Ocean, over the next 3-6 months. The ideal candidates will be committed and hardworking chefs with great drive and innovation and will oversee all kitchen operations of all outlets, including menu planning, cost and quality control, purchasing, supplies, budgeting and preparation. You will need to have international 5 star experience with a solid background in management and culinary expertise and you should have worked in Africa, the Indian Ocean or hardship locations. If you would like to be considered and become part of this growing International company, please forward your resume. Should you be suitable we will then share further details regarding this role.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(8, 'Executive Sous Chef', 'Egypt', 3300, '5 Star Resort Hotel in Egypt wishes to appoint a committed, hardworking Executive Sous Chef. The ideal candidate will work closely with the Executive Chef in completing the Food & Beverage department input into the overall hotel strategic plans. You will be responsible for contributing to menu creation, managing the daily kitchen operation and working with a multi-cultural kitchen brigade to deliver an excellent guest and team member experience, while managing food cost controls, maintaining sensitivity to local cultural traditions and adhering to religious beliefs in preparation and services of all food on premises. You will deliver the highest level of cuisine to all external and internal customers. To apply for this role you must have a minimum of 3 years experience as Executive Sous Chef in a 5 star hotel environment. The ability to communicate well in English and a proven track of food preparation, presentation and preservation knowledge is essential. This is a single status position. A good package is offered to the successful candidate. Only those of you who are shortlisted will be responded to.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(9, 'Chef de Cuisine', 'Russian Federation', 3000, 'Our client is seeking a Chef de Cuisine for a restaurant serving European cuisine and classic Russian dishes within a 5 star property in St. Petersburg. The ideal candidate will have the ability to fully manage their own kitchen to meet all quality, hygiene and operating standards, have a motivational and enthusiastic character and have excellent technical culinary skills. You will be responsible for delivering menus in keeping with the ethos and beliefs of the Company across the hotel, with consistency and quality of food and presentation at the highest level, whilst achieving targets in gross profit, food hygiene and health & safety. A candidate that has current or previous experience in the region as well as knowledge of the Russian language would be a plus. A good salary plus the usual benefits is offered to the successful applicant. Whilst we thank you for your interest, only those of you who are shortlisted will be contacted.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(10, 'Japanese Executive Chef', 'Macau', 10000, 'Our client, one of the worlds leading operators of Casinos and Integrated resorts, is looking for a Japanese Executive Chef for one of their most prestigious restaurants based in a dynamic and rapidly exposing leading city in Asia. We are looking for a Japanese superstar that has experience in a Michelin star environment and has a strong understanding of Michelin cuisine guidelines. The idea candidate will have a mixture of hotel and standalone restaurant experience, and a contemporary approach to Japanese cuisine. You will have extensive experience in Sushi, Omakase, Kaiseki and Teppanyaki style cooking, handling world class Japanese ingredients. Presentation and flavor balance will be of the highest levels and your communication and interpersonal skills will be second to none. To be considered for this role you will have a proven track record in a Michelin star working environment. You must have good English language skills, an outgoing personality and have the ability to host guest chefs for collaborations and special events at the restaurant and at other establishments on an International level. A good package is on offer. Only those shortlisted will be responded to.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(11, 'Teppanyaki Chef de Partie', 'Maldives', 1400, 'An opportunity has arisen for a Chef de Partie to join the team at a luxury Island Resort in the Maldives with experience working on a Teppani table. Clearly you will have a background and an understanding of Teppanyaki dishes and how to work at a Teppan table to give the guests the best experience possible. You should be eager and willing to learn and not be afraid of hard work. To apply you will have 1-2 years previous experience holding the same role in a 4/5 star property. This is a single status contract. Please be advised that only short listed candidates will be responded to.', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(12, 'Executive Housekeeper', 'Maldives', 3500, 'Our client is looking for an Executive Housekeeper for an Island Resort in the Maldives. The successful candidate will be responsible for the overall cleaning and stocking of guest rooms and to ensure the high standards of cleanliness in the hotel. You must have at least 5 years experience as Executive Housekeeper in the hotel industry and you will preferably have working experience on an island/cruise ship. You will need to have a guest focused personality with appropriate leadership and coaching style skills, a passion for detail and be a good communicator at all levels. This is a hands on role with emphasis on quality and guest relations. This role may also suit those of you looking for your first Executive Housekeeper position. A good package is on offer but only short listed candidates will be responded to.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(13, 'Executive Housekeeper', 'Saudi Arabia', 3000, 'We are searching for an Executive Housekeeper for a 5 star property in Saudi Arabia. You will be responsible for delivering quality housekeeping services to guest rooms, public facilities, and back of house areas of the property in a consistent, cost effective and safe manner, resulting in the highest standard of guest satisfaction. You will operate within department budgets through effective stock controls and well managed schedules and you will meet regularly with engineering and laundry departments to ensure smooth flow of supplies and repair works. We are looking for someone who will achieve high-quality standards at all times. To be considered for this role you will have held, or currently be holding, an Executive Housekeeper position in a 5 star property within the GCC and you will have International standard experience. The ability to communicate in Arabic would be beneficial. This is a single status contract. Please note that only shortlisted candidates will be responded to.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(14, 'Host/Hostess', 'Dubai', 800, '5 star Hotel in Dubai is seeking Host/Hostesses for a bar concept. As a Host/Hostess your main responsibility is to deliver an excellent experience to our guests. You will also be required to have extensive knowledge of menu offerings. Specifically, you will be responsible for greeting warmly and graciously all guests upon arrival, communicating effectively with guests and co-workers and have the ability to manage guest queries in a friendly, timely, and efficient manner. To apply you must have at least 1 years experience as a Host/Hostess. This is a single status contract. Please be advised that only short listed candidates will be responded to.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(15, 'Head Bartender/Mixologist', 'Dubai', 1600, 'Our client is currently seeking an experienced Head Bartender/Mixologist for a bar concept within a 5 star Hotel in Dubai. You will prepare and serve beverages in a speedy, efficient, friendly, and professional manner whilst ensuring that the bar is set and maintained with everything needed to run an effective operation, as well as maintaining the cleanliness of the outlet and set-up and breakdown of the bar. You will need to be highly motivated and enthusiastic and have great leadership and communication skills. To be considered for this role you must have at least 2 years of prior experience in a similar operational setting and you will have proven history of mixologist abilities, certificates obtained, participation in competitions. You will also be well updated with the new trends in the market with regards to beverages. The ability to create an ambient and vibrant atmosphere amongst the guests is paramount. Our client is looking for a flamboyant show character that can teach others and raise the standards of the bars operations. A good package is on offer and, whilst we thank you for your interest, you will only be contacted if you are shortlisted. \r\n\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(16, 'Italian Sous Chef', 'Bahrain', 2400, 'Luxury 5 Star Hotel in Bahrain is looking to appoint a Sous Chef for an Italian Restaurant. You will report to the Chef de Cuisine and play a major role in maintaining the standards in the outlet. Innovation, creativity, dynamism, passion and good people skills are required for this role and you will have a proven track record of strong commitment to job loyalty and consistency. To be considered, you must be trade qualified with appropriate certificates and reference letters/ diplomas and you will have a minimum of 3 years experience as Junior Sous Chef or similar working in an Italian kitchen. This is a single status contract. Only those applicants who are short listed will be responded to.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(17, 'Director of Sales & Marketing', 'Oman', 4900, 'We are currently seeking a Director of Sales & Marketing for this well established 5 star Hotel in Oman. The client is looking for someone who is strategic, innovative, able to lead the team and manage change. You will be an excellent communicator and driver of Sales with strong presentation skills, have the ability to create strong internal and external relationships and you must also have a good knowledge of the Middle Eastern market. To apply for this role you will have at least 3 years as a DOSM, with a minimum of 5 years in a senior sales position, within leading 5 star International properties and you will be able to demonstrate knowledge of all market segments. Please note that due to the specific requirements of this role, we will only respond to candidates who meet the above criteria.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(18, 'Executive Pastry Chef', 'Kuwait', 4900, 'Our clients operate a 5 star property in Kuwait and are currently seeking to appoint an experienced Executive Pastry Chef. You will be well experienced in wedding cakes, modern pastry & bakery techniques, chocolates, buffet decoration, Ice cream & Ice carving, ensuring that the highest standards are maintained at all times. The Pastry Chef will contribute ideas for new creations for desserts for both restaurant and banqueting. You will be highly motivated, talented and trained within the 5 star market. To apply for this role you should have at least 5 years experience as Executive Pastry Chef in a 5 star Hotel and you will be holding a Degree / Diploma in Hospitality Management or other related courses in Pastry. Only shortlisted candidates will be contacted.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(19, 'Chef de Cuisine', 'Kuwait', 3500, 'An opportunity has arisen for a Chef de Cuisine within a 5 star Hotel in Kuwait. The ideal candidate will be passionate about food and be committed to delivering an amazing guest experience. You will be responsible for contributing to menu creation and managing and training the kitchen brigade to deliver an excellent guest and team member experience. To be considered for this role you will have a minimum of 3 years experience as Chef de Cuisine and you will be holding a Degree / Diploma in Hospitality Management or other related field. You will ideally have an understanding of the All Day Dining concept, as well as knowledge of Italian/Mediterranean cuisine. GCC experience would be beneficial. A good salary plus benefits is on offer. Please note only shortlisted candidates will be contacted.\r\n\r\n\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41'),
(20, 'Food & Beverage Manager', 'India', 5000, 'We are currently seeking a Food & Beverage Manager for a 5 star Hotel in Mumbai. The ideal candidate will assume full responsibility for the day-to-day operation of this department and will have a thorough knowledge of food and beverage operations including foods, beverages, supervisory aspects, service techniques, and guest interaction. To be considered for this role you must have F&B experience within a highly recognised Hotel company in a cosmopolitan City. Our client is ideally looking for an Assistant F&B Manager who is looking to progress in their career. This is a single status contract. We will only be able to respond to those of you who are shortlisted.\r\n', '2021-04-05 14:46:41', '2021-04-05 14:46:41');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `positions`
--
ALTER TABLE `positions`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `positions`
--
ALTER TABLE `positions`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
